In [5]:
import pandas as pd
menu = pd.Series(['비빔밥', '김치찌개', '된장찌개'])
price = pd.Series([10000, 9000, 8000])

df = pd.DataFrame({'메뉴': menu, '가격': price})
df

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [6]:
df.to_csv('menu.csv', index=False)   # index=False: 행번호 저장 안 함(제출 파일 기본)

In [9]:
df2 = pd.read_csv('02.csv')        # 파일 → DataFrame
df2

     상위 시도지역코드  시군구지역코드  시군구명
0           11    11110   종로구
1           11    11140    중구
2           11    11170   용산구
3           11    11200   성동구
4           11    11215   광진구
..         ...      ...   ...
245         48    48870   함양군
246         48    48880   거창군
247         48    48890   합천군
248         49    49110   제주시
249         49    49130  서귀포시

[250 rows x 3 columns]

In [23]:
# print('모양:', df2.shape)
# print('열 이름:', df2.columns.tolist())
# print('결측치:', df2.isnull().sum().to_dict())
# print(df2['상위 시도지역코드'].value_counts())   # 범주별 개수(타겟 분포 확인의 핵심)
# print(df2.describe())                 # 수치열 요약
df2.info()                            # 열별 타입·결측

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   상위 시도지역코드  250 non-null    int64
 1   시군구지역코드    250 non-null    int64
 2   시군구명       250 non-null    object
dtypes: int64(2), object(1)
memory usage: 6.0+ KB

In [28]:
import numpy as np
df3 = pd.DataFrame({'가격': [10000, np.nan, 8000], '원산지': ['국내산', None, '국내산']})
df3

        가격   원산지
0  10000.0   국내산
1      NaN  None
2   8000.0   국내산

In [35]:
# print(df3['가격'].fillna(df3['가격'].median()))
print(df3['원산지'].mode()[0])

# df3['가격']  = df3['가격'].fillna(df3['가격'].median())       # 수치 → 중앙값
# df3['원산지'] = df3['원산지'].fillna(df3['원산지'].mode()[0])   # 범주 → 최빈값
# df3

국내산

In [40]:
grade = pd.Series(['합격', '불합격', '합격'])
grade.map({'합격': 1, '불합격': 0})   # 글자 라벨 → 숫자(04 타겟 0/1 변환) → [1, 0, 1]
               # 범주형 글자 열 → 0/1 열(원핫 인코딩)

0    1
1    0
2    1
dtype: int64

In [38]:
# pd.concat([df2.head(1), df2.tail(1)], axis=0)   # 위아래로 이어붙이기(train+test)
# df2.groupby('원산지')['가격'].mean()             # 그룹별 집계(EDA·작업형1)

In [39]:
pd.get_dummies(df2)

,상위 시도지역코드,시군구지역코드,시군구명_가평군,시군구명_강남구,시군구명_강동구,시군구명_강릉시,시군구명_강북구,시군구명_강서구,시군구명_강진군,시군구명_강화군,...,시군구명_함평군,시군구명_합천군,시군구명_해남군,시군구명_해운대구,시군구명_홍성군,시군구명_홍천군,시군구명_화성시,시군구명_화순군,시군구명_화천군,시군구명_횡성군
0,11,11110,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,11,11140,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,11,11170,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,11,11200,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,11,11215,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,48,48870,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
246,48,48880,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
247,48,48890,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
248,49,49110,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
249,49,49130,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [41]:
df2.head(1)

   상위 시도지역코드  시군구지역코드 시군구명
0         11    11110  종로구

In [42]:
df2.tail(1)

     상위 시도지역코드  시군구지역코드  시군구명
249         49    49130  서귀포시

In [43]:
pd.concat([df2.head(1), df2.tail(1)], axis=0)

     상위 시도지역코드  시군구지역코드  시군구명
0           11    11110   종로구
249         49    49130  서귀포시

In [50]:
df5 = pd.DataFrame({
    '메뉴':  ['비빔밥', '김치찌개', '된장찌개','오무라이스','초밥','라멘','돈까스'],
    '타입': ['한식','한식','한식','양식','일식','일식','양식'],
    '가격':  [10000, 9000, 8000,5000,6000,7000,8000],
    '원산지': ['국내산', '국내산', '국내산', '국내산', '국내산', '국내산', '국내산']
})
df5.groupby('타입')['가격'].mean()

타입
양식    6500.0
일식    6500.0
한식    9000.0
Name: 가격, dtype: float64

In [46]:
df2.groupby('원산지')['가격'].mean()