In [36]:
import pandas as pd

cafe = pd.DataFrame({
    '메뉴':   ['아메리카노', '카페라떼', '녹차라떼', '자몽에이드', '레몬에이드'],
    '가격':   [4000, 4500, 5000, 5500, 5000],
    '분류':   ['커피', '커피', '논커피', '음료', '음료'],
    '재고':   [30, 12, 8, 20, 15]
})
cafe

      메뉴    가격   분류  재고
0  아메리카노  4000   커피  30
1   카페라떼  4500   커피  12
2   녹차라떼  5000  논커피   8
3  자몽에이드  5500   음료  20
4  레몬에이드  5000   음료  15

In [39]:
# 문제 1. Series vs DataFrame
# 메뉴 열을 두 가지 방법으로 뽑고, 각각의 타입을 출력하라.

# (1) Series로 뽑기
# (2) DataFrame(표 모양 유지)으로 뽑기
# (3) type()으로 두 결과의 타입이 다름을 확인
# 💡 힌트: 대괄호 개수 차이



cafe_series = pd.Series(cafe['메뉴'])
cafe_series

0    아메리카노
1     카페라떼
2     녹차라떼
3    자몽에이드
4    레몬에이드
Name: 메뉴, dtype: object

In [19]:
cafe_dataFrame = pd.DataFrame(cafe_series)
cafe_dataFrame

      메뉴
0  아메리카노
1   카페라떼
2   녹차라떼
3  자몽에이드
4  레몬에이드

In [29]:
print(type(cafe_series),'\n',type(cafe_dataFrame))

<class 'pandas.core.series.Series'>
 <class 'pandas.core.frame.DataFrame'>

In [40]:
# 문제 2. loc vs iloc
# (1) loc을 사용해 인덱스 1~3 행의 메뉴, 가격 열을 출력하라.
# (2) iloc을 사용해 앞 3행, 앞 2열을 출력하라.
# (3) 두 결과에서 몇 개의 행이 나왔는지 비교하고, 왜 다른지 한 줄로 설명하라.
# 💡 힌트: loc은 끝 포함, iloc은 끝 제외

cafe.loc[1:3]

      메뉴    가격   분류  재고
1   카페라떼  4500   커피  12
2   녹차라떼  5000  논커피   8
3  자몽에이드  5500   음료  20

In [33]:
cafe.iloc[0:3, 0:2]

      메뉴    가격
0  아메리카노  4000
1   카페라떼  4500
2   녹차라떼  5000

In [45]:
# 문제 3. 열 추가 + 조건부 값 수정
# (1) 가격의 10%를 부가세로 계산한 부가세 열을 추가하라. (정수형으로)
# (2) 가격과 부가세를 더한 최종가 열을 추가하라.
# (3) 분류가 '음료'인 행만 재고를 50으로 바꿔라.
# 💡 힌트: .astype(int), df.loc[조건, '열'] = 값


cafe['부가세'] = (cafe['가격']*0.9).astype(int)
cafe

      메뉴    가격   분류  재고   할인가   부가세
0  아메리카노  4000   커피  30  3600  3600
1   카페라떼  4500   커피  12  4050  4050
2   녹차라떼  5000  논커피   8  4500  4500
3  자몽에이드  5500   음료  20  4950  4950
4  레몬에이드  5000   음료  15  4500  4500

In [48]:
cafe.loc[cafe['분류']=='음료', '재고'] = 50
cafe

      메뉴    가격   분류  재고   할인가   부가세
0  아메리카노  4000   커피  30  3600  3600
1   카페라떼  4500   커피  12  4050  4050
2   녹차라떼  5000  논커피   8  4500  4500
3  자몽에이드  5500   음료  50  4950  4950
4  레몬에이드  5000   음료  50  4500  4500

In [58]:
# 문제 4. 조건 필터 + 정렬
# (1) 분류가 '커피'가 아니면서 가격이 5000 이상인 행만 골라라.
# (2) 그 결과를 가격 내림차순으로 정렬하라.
# (3) 정렬된 결과에서 메뉴, 가격 열만 남겨라.
# 💡 힌트: 조건은 각각 괄호로 감싸고 &로 연결, != 사용, sort_values(by=..., ascending=False)

cafe[(cafe['분류'] != '커피') & (cafe['가격'] >= 5000)]

      메뉴    가격   분류  재고   할인가   부가세
2   녹차라떼  5000  논커피   8  4500  4500
3  자몽에이드  5500   음료  50  4950  4950
4  레몬에이드  5000   음료  50  4500  4500

In [60]:
cafe[(cafe['분류'] != '커피') & (cafe['가격'] >= 5000)].sort_values(by='가격', ascending=False)

      메뉴    가격   분류  재고   할인가   부가세
3  자몽에이드  5500   음료  50  4950  4950
2   녹차라떼  5000  논커피   8  4500  4500
4  레몬에이드  5000   음료  50  4500  4500

In [ ]:
# 문제 5. 집계 → 이름 변경 → 저장
# (1) 분류별 가격의 평균을 구하라.
# (2) 원본 cafe에서 재고 열을 삭제하라.
# (3) 열 이름을 메뉴→name, 가격→price, 분류→category로 바꿔 cafe_en 변수에 담아라.
# (4) cafe_en을 cafe_en.csv로 저장하되 행번호는 저장하지 않게 하라.
# (5) 저장한 파일을 다시 읽어 head()와 info()로 확인하라.
# 💡 힌트: groupby(), drop(columns=[...]), rename(columns={...}), to_csv(index=False), read_csv()